itemsA = {"蘋果", "香蕉", "鳳梨", "芭樂"}
itemsB = {"鳳梨", "蘋果", "水梨", "蓮霧"}
itemsA.remove("蘋果")
itemsB.remove("蓮霧")
itemsA.add(input())
itemsA.add(input())
itemsB.add(input())
itemsB.add(input())
a,b=list(itemsA),list(itemsB)
a.sort()
b.sort()
print("iA:",a)
print("iB:",b)
union=itemsA.union(itemsB)
intersection=itemsA.intersection(itemsB)
a=list(union)
a.sort()
print("union:",a)
a=list(intersection)
a.sort()
print("intersection:",a)
a=list(itemsA-intersection)
a.sort()
print("A diff B:",a)
a=list(itemsB-intersection)
a.sort()
print("B diff A:",a)
a=list(union-intersection)
a.sort()
print("A xor B:",a)
